import type { NextPage } from 'next'
import React, { useState } from 'react'
import Head from 'next/head'
import {
  Link,
  Input,
} from '@chakra-ui/react';
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  var ethereum_address = require('ethereum-address');
  const [address, setAddress] = useState<string>('')
  const handleInputChange = (e:any) => {
    const val = e.target.value;
    setAddress(val)
    console.log(val);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Input
          type='text'
          fontFamily='Dm Sans'
          placeholder='Wallet Address'
          value={address}
          onChange={(e) => {handleInputChange(e)}}
          w="50%"
        />
        {ethereum_address.isAddress(address) ? (
          <div id="world-id-container">
            <Link
              fontFamily='Dm Sans'
              href={`https://developer.worldcoin.org/hosted/wid_c4a8f9955a2ab7a9d01b24f9c279c95d?signal=${address}`}
            >
              Verify with World ID
            </Link>
          </div>
        ) : (
          <></>
        )}
      </main>
    </div>
  )
}

export default Home
