import type { NextPage } from 'next'
import React, { useState } from 'react'
import Head from 'next/head'
import {
  Link,
  Input,
  Button
} from '@chakra-ui/react';
import styles from '../styles/Home.module.css'
import { ethers } from 'ethers'

const provider = new ethers.providers.JsonRpcProvider(process.env.API_URL)

const Home: NextPage = () => {
  var ethereum_address = require('ethereum-address');
  const [address, setAddress] = useState<string>('')
  const handleInputChange = (e:any) => {
    const val = e.target.value;
    setAddress(val)
    console.log(val);
  }
  const handleClick = () => {
    fetch(`/api/verify`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(address),
    });
  }

  const handleENS = async () => {
    const res = await provider.resolveName(address);
    console.log(res);

    setAddress(res as string);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Input
          type='text'
          fontFamily='Dm Sans'
          placeholder='Wallet Address or ENS'
          value={address}
          onChange={(e) => {handleInputChange(e)}}
          w="50%"
        />
        {ethereum_address.isAddress(address) ? (
          <div id="world-id-container">
            <Link
              fontFamily='Dm Sans'
              href={`${process.env.WORLD_ID_URI}${address}`}
            >
              Verify with World ID
            </Link>
          </div>
        ) : (
          // <Link
          //   fontFamily='Dm Sans'
          //   href={`https://developer.worldcoin.org/hosted/wid_68e8cff610043f0b03888aa7fcf1907e?signal=${address}`}
          // >
          //   Verify with World ID
          // </Link>
          <Button
          onClick={handleENS}
          >use ENS</Button>
        )}
      </main>
    </div>
  )
}

export default Home
